version: "3.8"
services:
  web:
    build: ./app
    image: 904425387266.dkr.ecr.us-east-2.amazonaws.com/ufc_docker_aws:ufc_docker_aws_web
    command: gunicorn ufc.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=ufc_rankings_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=ufc.ctj8rhrpn1nh.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-3-18-183-239.us-east-2.compute.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 904425387266.dkr.ecr.us-east-2.amazonaws.com/ufc_docker_aws:ufc_docker_aws_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: